FROM busybox
MAINTAINER Scotty Waggoner <ozzieorca@gmail.com>

RUN mkdir -p /data/db
RUN mkdir -p /data/images

# Define default command.
CMD ["bash"]

#Docker Build
#cd ~/docker-builder/data-only && docker build -t quay.io/ozzieorca/data-only . && docker push quay.io/ozzieorca/data-only; cd