FROM ubuntu
MAINTAINER Scotty Waggoner <ozzieorca@gmail.com>

# Install.
RUN \
  sed -i 's/# \(.*multiverse$\)/\1/g' /etc/apt/sources.list && \
  apt-get update && \
  apt-get -y upgrade && \
  apt-get install -y build-essential && \
  apt-get install -y software-properties-common && \
  apt-get install -y byobu curl git htop man zip unzip vim wget && \
  rm -rf /var/lib/apt/lists/*

# Set environment variables.
ENV HOME /root

# Define working directory.
WORKDIR /root

# Define default command.
CMD ["bash"]

#Docker Build
#cd ~/docker-builder/ubuntu && docker build -t quay.io/ozzieorca/ubuntu . && docker push quay.io/ozzieorca/ubuntu; cd